# _config.yml
title: Ben Grelk's Blog
email: ben.grelk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal blog of Ben Grelk, a Software Engineering student at the University of Nebraska-Lincoln.
  Posts may cover a variety of topics, including professional experiences, programming technologies,
  or other technology-related fields.
baseurl: "/blog"
url: "https://benjamingrelk.github.io"
github_username:  BenjaminGrelk

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
